apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels:
    app: fleetman-webapp
spec:
  selector:
    app: webapp
  ports: 
  - name: http
    port: 80 
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata: 
  name: fleetman-queue
  labels:
    app: fleetman-queue
spec:
  selector: 
    app: queue
  ports:
  # - name: http
  #   port: 8161
  #   nodePort: 30010
    # targetPort: 8161
  - name: endpoint
    port: 61616
  type: ClusterIP    # for testing u can give it a NodePort

---
apiVersion: v1
kind: Service
metadata: 
  name: fleetman-position-tracker
  labels:
    app: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
  - name: http
    port: 8080     # service port.
 
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata: 
  name: fleetman-api-gateway
  labels:
    app: fleetman-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8080     # service port.
  type: ClusterIP

